# Generated by Django 3.2.8 on 2024-01-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('premises_usage', models.CharField(max_length=255)),
                ('meter_type', models.CharField(max_length=255)),
                ('house_address', models.CharField(max_length=255)),
                ('building_type', models.CharField(max_length=255)),
                ('electrical_personnel_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('lincence_number', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('sdate', models.DateField(max_length=255)),
                ('elecrical_point_list', models.TextField(null=True)),
                ('total_wattage', models.CharField(max_length=225, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meterform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
