# Generated by Django 3.2.8 on 2024-01-30 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalPersonnelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_profession', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MeterApplication',
            fields=[
                ('application_number', models.CharField(max_length=255, null=True, unique=True)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('premises_usage', models.CharField(max_length=255, null=True)),
                ('meter_type', models.CharField(max_length=255, null=True)),
                ('house_address', models.CharField(max_length=255, null=True)),
                ('building_type', models.CharField(max_length=255, null=True)),
                ('user_apply', models.CharField(max_length=255, null=True)),
                ('electrical_personnel_name', models.CharField(max_length=255, null=True)),
                ('account_number', models.CharField(max_length=255, null=True)),
                ('licence_number', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('sdate', models.DateField(max_length=255, null=True)),
                ('elecrical_point_list', models.TextField(null=True)),
                ('total_wattage', models.CharField(max_length=225, null=True)),
                ('local_gov_area', models.CharField(max_length=225, null=True)),
                ('area_office', models.CharField(max_length=225, null=True)),
                ('regional_office', models.CharField(max_length=225, null=True)),
                ('state', models.SlugField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PremisesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premises_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PremisesUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=25)),
            ],
        ),
    ]
