# Generated by Django 3.2.8 on 2024-01-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterapplication',
            old_name='elecrical_point_list',
            new_name='electricalList',
        ),
    ]
