# Generated by Django 3.2.8 on 2024-01-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterapplication',
            old_name='lincence_number',
            new_name='licence_number',
        ),
    ]
