# Generated by Django 3.2.8 on 2024-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterapp', '0002_rename_lincence_number_meterapplication_licence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalPersonnelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_profession', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PremisesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premises_name', models.CharField(max_length=25)),
            ],
        ),
    ]
