# Generated by Django 3.2.8 on 2024-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterapp', '0003_electricalpersonnelcategory_metertype_premisestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremisesUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=25)),
            ],
        ),
    ]
