# Generated by Django 3.2.8 on 2024-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterapp', '0004_premisesusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterapplication',
            name='area_office',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='meterapplication',
            name='local_gov_area',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='meterapplication',
            name='regional_office',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
